#!/bin/sh
# Author: Qiu
# License: BSD 2-Clause "Simplified" License
# This script gets the CWD of the focued view. On error xcwd is used -
# this allows the script to also work on xwayland views.
# Tested on FreeBSD and Linux.

# Get the view tree
getTree() { swaymsg -t get_tree; }
# Find the focused view in the tree
filter() { jq -c 'getpath(path(.. .focused? // empty)[:-1]).pid'; }

# Find the PID of the process
PID=$(getTree | filter)

# Print the current working directory
if [ "$(uname)" == "FreeBSD" ]
then
	STAT="$(procstat -f $PID 2>/dev/null)"
	[ "$?" -eq "0" ] && (echo "$STAT" | awk '$3 == "cwd" { print $10 }') || xcwd
elif [ "$(uname)" == "Linux" ]
then
	readlink -e "/proc/$PID/cwd" 2>/dev/null || xcwd
fi
